name: Bug Report
description: Report a bug or unexpected behavior
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the sections below so we can reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Add the plugin dependency to build.gradle
        2. Create a controller with action '...'
        3. Make a request to '...'
        4. Inspect the response headers
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include the Server-Timing header value if relevant.
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: The version of grails-server-timing you are using.
      placeholder: "0.0.1-SNAPSHOT"
    validations:
      required: true

  - type: input
    id: grails-version
    attributes:
      label: Grails Version
      placeholder: "7.0.7"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Output of `java -version`
      placeholder: "17.0.17"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (logs, configuration, screenshots, etc.).
