name: Feature Request
description: Suggest a new feature or enhancement
labels: [ "feature" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe what you'd like and why it would be valuable.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration with the current plugin?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which part of the plugin does this affect?
      options:
        - Core timing (filter/interceptor)
        - Configuration
        - Custom metrics API
        - Documentation
        - Build / tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or references that would help explain the feature.
