name: "Code Style"
on:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'main'
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  code-style:
    name: "Code Style"
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v6
      - name: "Export .sdkmanrc properties"
        uses: apache/grails-github-actions/export-gradle-properties@asf
        with:
          file: ".sdkmanrc"
          prefix: "SDKMANRC_"
      - name: "Determine Java Version"
        run: echo "SDKMANRC_java=${{ env.SDKMANRC_java }}" | sed 's/-.*//' >> $GITHUB_ENV
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: ${{ env.SDKMANRC_java }}
      - name: "Export gradle.properties properties"
        uses: apache/grails-github-actions/export-gradle-properties@asf
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: ${{ env.ciBuildScanPublish }}
          build-scan-terms-of-use-url: ${{ env.ciBuildScanTermsOfUseUrl }}
          build-scan-terms-of-use-agree: ${{ env.ciBuildScanTermsOfUseAgree }}
      - name: "🎨 Run code style checks"
        run: >
          ./gradlew codeStyle
          --continue
          --stacktrace
